### ISSUE TITLE
Error! No private key found for this message. Required private key IDs: ...

### ISSUE THREAD

**Issue by dbgdngit** [mailvelope/mailvelope#267]
Chrome Browser
Win 7 and Mac OSX

Cannot decrypt received emails or emails that were sent and decrypted successfully previously.
Only been happening in the past 5 or 6 days
Happens with keys generated in Mailvelope or imported from GPG

**Comment by dbgdngit** [comment]
The other situation I get is that is there is no error message and the decryption progress disk keeps spinning but never completes. Again this on messages that decrypted before.

**Comment by toberndo** [comment]
The last stable release of Mailvelope was in Nov. 2014, so this issue could be related to a browser update. In general stability of decrypting messages with attachments (PGP/MIME) improved in the latest pre-releases. If you are able to test with https://github.com/mailvelope/mailvelope/releases I would be interested in feedback. Otherwise the next stable release will be end of next week.

**Comment by dbgdngit** [comment]
Browser update was initial thought too. Thanks I will try the latest dev release

**Comment by dbgdngit** [comment]
ok. Re-importing public keys today seems to have fixed the issue. I'm using version 012.03b but others still on 0.11.0_0 did the same and it works. This implies a Chrome issue.

**Comment by dbgdngit** [comment]
Definite Chrome bug in content verification - which was fixed in version 40. Somehow it corrupted the keystore

**Comment by grantmeaccess** [comment]
I am getting the same error in Chromium Version 43.0.2357.81 Ubuntu 14.04 (64-bit). I have tried reimporting keys. I just installed Mailvelope this week, so it's the current version.

**Comment by whyrao** [comment]
Yep, Chrome is the problem. I tried debugging for several hours using only Chrome with no luck. Just tried on both Chrome and Firefox. Firefox works fine; Chrome still doesn't. 

Chrome: Version 57.0.2987.133 (64-bit)
Firefox: 52.0.2 (64-bit)
MacOS: 10.12.4Beta
