### ISSUE TITLE
MIME headers shown for multipart message, with escaped UTF8 characters

### ISSUE THREAD

**Issue by elecnix** [mailvelope/mailvelope#31]
I'm opening an old e-mail that goes like this:

```
Content-Type: multipart/encrypted; protocol="application/pgp-encrypted";
boundary="71GDUHkQ4uogWNBm"
Content-Disposition: inline
User-Agent: Mutt/1.5.13 (2007-09-12)

--71GDUHkQ4uogWNBm
Content-Type: application/pgp-encrypted
Content-Disposition: attachment

Version: 1

--71GDUHkQ4uogWNBm
Content-Type: application/octet-stream
Content-Disposition: inline; filename="msg.asc"

-----BEGIN PGP MESSAGE-----
Version: GnuPG v1.4.6 (GNU/Linux)

0oaZu+M2W3OrVJ+T3IhGBBARAgAGBQI+KBvzAAoJEGQOZC4vLwze
....
```

Mailvelope recognizes the encrypted part, but when decrypted, some headers are displayed, and UTF-8 characters are not decoded:

```
Content-Type: text/plain; charset=utf-8 
Content-Disposition: inline 
Content-Transfer-Encoding: quoted-printable 

Hello! R=C3=A9fl=C3=A9chis!
```

**Comment by momo13** [comment]
I am observing the same behavior as duckdable describes. Same question: Bug or known limitation?

**Comment by toberndo** [comment]
@momo13 Should be fixed in the latest pre-release: https://github.com/mailvelope/mailvelope/releases

**Comment by momo13** [comment]
@toberndo Thanks! Looks good for quoted-printable encoded messages.

**Comment by momo13** [comment]
@toberndo Sorry, my response was too fast. I wrongly checked with an Email that had an alternative HTML part. For a quoted printable part I still get this displayed:
```
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain;
charset=utf-8

=C3=84H
```

**Comment by toberndo** [comment]
Looks like this message has no mulitpart/encrypted content type and therefore is no valid PGP/MIME.

According to [RFC3156](https://tools.ietf.org/html/rfc3156): `OpenPGP encrypted data is denoted by the "multipart/encrypted" content type`

Which implementation are you using to generate this message?
