### ISSUE TITLE
Error! Could not read this encrypted message: Error: Support for Symmetrically Encrypted Data Packet (Tag 9) deactivated.

### ISSUE THREAD

**Issue by digital-shokunin** [mailvelope/mailvelope#341]
This started with the most recent update when trying to decrypt a message.. There are lots of other users reporting the same on the Chrome Web Store. Right now the extension is unusable.

**Comment by gomez77** [comment]
Based on the changed log I changed "enforce_integrity_protection: true," to "enforce_integrity_protection: false," in ..\1.2.2_0\dep\openpgp.js but it seems not working?

I get the same "error" message. Is there a possibility to configure the behavior?

**Comment by donnamaui** [comment]
Having the same message when trying to decrypt (clicking on lock). Any help would be appreciated.

**Comment by travisterrell** [comment]
Unfortunately, I am experiencing the same problem. I confirmed the problem by also trying to decrypt older messages that I've successfully decrypted before. These messages would also no longer decrypt.

**Comment by toberndo** [comment]
Fix is available with the following builds:
https://build.mailvelope.com/nightly/mailvelope.2015-10-27.chrome.crx
https://build.mailvelope.com/nightly/mailvelope.2015-10-27.chrome.zip
https://build.mailvelope.com/nightly/mailvelope.2015-10-27.firefox.xpi

Please check if you can decrypt your messages as before. Especially the XPI package for Firefox can be used to update your existing Mailvelope installation.

**Comment by gomez77** [comment]
It is working with Firefox and the new build

**Comment by toberndo** [comment]
@gomez77 Thanks for testing. There is now a new config option `ignore_mdc_error`(https://github.com/mailvelope/openpgpjs/commit/b66093590a8aeca744a1ea5c9b5a9728738f1ad9) which is aligned to the same option in GPG (http://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=commit;h=625e292108cc0fd9077769587a8c22abe7805e33)

**Comment by travisterrell** [comment]
I can confirm that the new build has resolved the reported bug in Chrome.


Thank you,

Travis J. Terrell
travis@travisterrell.com


--

**Comment by shopps** [comment]
I was having this issue so I installed the linked update for firefox but now I just get "error: error decrypting message" with no further details.

**Comment by donnamaui** [comment]
Also getting this on chrome fix.

**Comment by toberndo** [comment]
@shopps @donnamaui In Mailvelope v1.2.3 we implemented the same security checks that will be present in GPG 2.1.9: decryption of PGP messages with modern cipher and without integrity protection will fail.
If possible please provide some details about the messages that cause these errors (public key, which PGP client).
Thanks.

**Comment by wyllys66** [comment]
This is still a problem in 1.3.0 in Chrome.  I cannot read many messages sent from older GPG clients due to the strict MDC checking policy.  This "feature" renders the extension largely useless.  Please add an option that makes it easy to relax the strict checking so I can decrypt my incoming messages.

**Comment by toberndo** [comment]
@wyllys66 So far feedback from ~10 users is that the less strict check in 1.2.3 fixed all compatibility issues. Which GPG client are you having problems with?

**Comment by wyllys66** [comment]
gpg (GnuPG/MacGPG2) 2.0.28

The "ignore_mdc_error" flag defaults to false, how do I change it to true without hacking the extension code itself?

**Comment by toberndo** [comment]
There is no way to change the flag at the moment in the settings.

**Comment by wyllys66** [comment]
OK, so what is the recommended way to enable that flag?

**Comment by toberndo** [comment]
@wyllys66 GPG 2.0.28 is a recent version. GPG uses MDC by default for many years. You would need to explicitly opt out with `--disable-mdc`. But who would do that?

**Comment by wyllys66** [comment]
The problem is that I can decrypt the same messages with no error or warning with gpg and with GPGTools.  When I do it on the command line the only warning I get is this:

"gpg: WARNING: message was not integrity protected"
The exit status code is still 0 and I can read the decrypted message.

Practically speaking, I still want to see the message if it decrypted correctly, even if it wasn't integrity protected.  Mailvelope should just show a warning about the missing integrity protection and leave it to the recipient to decide what to do about it.  The recipient has no control over how the original message was created and the sender may not even know that their PGP generator is out of date, but that's a policy issue and should not prevent the message from being displayed.

**Comment by toberndo** [comment]
The current OpenPGP.js API does not support warning messages. Failing on mdc error was an easy fix for a security issue and should not cause problems for the 99,9% use case. I'm not saying we can not fix this and displaying the warning directly to the user is an option. But I first want to understand better under which circumstances such mdc free messages is created.

**Comment by wyllys66** [comment]
I get messages from a PGP encrypted web form that uses "VerySimple PHP-GPG v1.4.7", which apparently doesn't generate an MDC.  I'll try working with the author of that plugin to address the issue, but I still think Mailvelope is being too strict.

**Comment by shopps** [comment]
I am also having this issue with encrypted mail sent using the same PHP
script, using Firefox and Roundcube.

Steven Hopps <mailto:shopps@pridetechdesign.com> Ph:424.888.0443 PGP
<http://www.pridetechdesign.com/shopps.public.asc>
Visit Pride Tech Design Website <http://www.pridetechdesign.com>
Portfolio <http://www.pridetechdesign.com/portfolio> . Pricing
<http://www.pridetechdesign.com/services> . Testimonials
<http://www.pridetechdesign.com/testimonials> . About Me
<http://www.pridetechdesign.com/about>
= Ask about my Security Tune-Up & 24/7 Server Monitoring! =

**Comment by DanielRuf** [comment]
The nly solution is the flag mentioned earier We can not add the MDC packet after the ecryption.

A future version of php-gpg may add a MDC packet.

**Comment by shopps** [comment]
How do we enable that flag when using mailvelope?

Steven Hopps <mailto:shopps@pridetechdesign.com> Ph:424.888.0443 PGP
<http://www.pridetechdesign.com/shopps.public.asc>
Visit Pride Tech Design Website <http://www.pridetechdesign.com>
Portfolio <http://www.pridetechdesign.com/portfolio> . Pricing
<http://www.pridetechdesign.com/services> . Testimonials
<http://www.pridetechdesign.com/testimonials> . About Me
<http://www.pridetechdesign.com/about>
= Ask about my Security Tune-Up & 24/7 Server Monitoring! =

**Comment by DanielRuf** [comment]
@shopps I am not sure but did you already try this? https://github.com/mailvelope/mailvelope/issues/341#issuecomment-151784288

Contributors are very welcome to help us with the MDC feature https://github.com/jasonhinkle/php-gpg/issues/18

**Comment by shopps** [comment]
How do I modify that config option? Do I have to compile mailvelope
myself? I've never done any extension development so I have no idea how
that works.

Steven Hopps <mailto:shopps@pridetechdesign.com> Ph:424.888.0443 PGP
<http://www.pridetechdesign.com/shopps.public.asc>
Visit Pride Tech Design Website <http://www.pridetechdesign.com>
Portfolio <http://www.pridetechdesign.com/portfolio> . Pricing
<http://www.pridetechdesign.com/services> . Testimonials
<http://www.pridetechdesign.com/testimonials> . About Me
<http://www.pridetechdesign.com/about>
= Ask about my Security Tune-Up & 24/7 Server Monitoring! =

**Comment by DanielRuf** [comment]
Browse extensions are writen in JavaScript and HTML, you can easily change the code, there is no compilation needed

**Comment by shopps** [comment]
Where are the files stored? I looked in the mozilla folder under
appdata, I checked all the extensions in /profile/my.default/extensions/
but none of them seem to be mailvelope, however it is installed and active..

Steven Hopps <mailto:shopps@pridetechdesign.com> Ph:424.888.0443 PGP
<http://www.pridetechdesign.com/shopps.public.asc>
Visit Pride Tech Design Website <http://www.pridetechdesign.com>
Portfolio <http://www.pridetechdesign.com/portfolio> . Pricing
<http://www.pridetechdesign.com/services> . Testimonials
<http://www.pridetechdesign.com/testimonials> . About Me
<http://www.pridetechdesign.com/about>
= Ask about my Security Tune-Up & 24/7 Server Monitoring! =

**Comment by wyllys66** [comment]
Why not just add an option on the configuration page for the extension to toggle the flag?  Whats the point of having an option if its not easily accessible to the users?

**Comment by shopps** [comment]
My thoughts too..

Steven Hopps <mailto:shopps@pridetechdesign.com> Ph:424.888.0443 PGP
<http://www.pridetechdesign.com/shopps.public.asc>
Visit Pride Tech Design Website <http://www.pridetechdesign.com>
Portfolio <http://www.pridetechdesign.com/portfolio> . Pricing
<http://www.pridetechdesign.com/services> . Testimonials
<http://www.pridetechdesign.com/testimonials> . About Me
<http://www.pridetechdesign.com/about>
= Ask about my Security Tune-Up & 24/7 Server Monitoring! =

**Comment by DanielRuf** [comment]
php-gpg 1.6.0 is now available and will add a MDC packet to encrypted messages. But old messages will still throw a warning about the missing MDC packet.
