### ISSUE TITLE
[Bug] `gnupg`  reported as not installed by Mailvelope when it is installed.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [mailvelope/mailvelope#814]
Potentially caused by https://github.com/mailvelope/mailvelope/issues/810#issue-1593637886.

**Diagnosis**

1.	> ![image](https://user-images.githubusercontent.com/42837531/233389980-dde2b22a-3abf-48c5-8a18-957faa6fec99.png)

1.	<blockQuote>
	
	```.log
	rokejulianlockhart@RQN6C6:~> script -a
	Script started, output log file is 'typescript'.
	rokejulianlockhart@RQN6C6:~> pwsh
	PowerShell 7.3.4
	PS /home/rokejulianlockhart> sudo zypper install gnupg                     
	[sudo] password for root: 
	Loading repository data...
	Reading installed packages...
	'gnupg' not found in package names. Trying capabilities.
	'gpg2' providing 'gnupg' is already installed.
	Resolving package dependencies...
	Nothing to do.
	PS /home/rokejulianlockhart>
	```
	
	</blockQuote>

**Comment by shamefulCake1** [comment]
Wrong version? Mailvelope requires super new versions of gnupg and gpgme.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/mailvelope/mailvelope/issues/814#issuecomment-1986709685

@shamefulCake1, which versions? The current versions in my OS's default repository are https://download.opensuse.org/repositories/openSUSE:/Factory/standard/x86_64/gpgme-1.23.2-4.1.x86_64.rpm and https://download.opensuse.org/repositories/openSUSE:/Factory/standard/x86_64/gpg2-2.4.4-1.2.x86_64.rpm.

**Comment by shamefulCake1** [comment]
@RokeJulianLockhart 

Okay, I am wrong. The documentation page https://github.com/mailvelope/mailvelope/wiki/Mailvelope-GnuPG-integration is saying 

```
GnuPG (min. version 2.4.0) is installed on the system
gpgme (min. version 1.19.0) is installed on the sytem
```

mine are lower, so I naturally assumed that to be the issue. 
Maybe not.

**Comment by rimmer** [comment]
Since the mailvelope version on [FF Addons Page](https://addons.mozilla.org/en-US/firefox/addon/mailvelope/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) isn't old anymore, I assume the issue is fixed? Let us know otherwise

**Comment by SuperdukeGates** [comment]
> Since the mailvelope version on [FF Addons Page](https://addons.mozilla.org/en-US/firefox/addon/mailvelope/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) isn't old anymore, I assume the issue is fixed? Let us know otherwise

I still have the same problem. I use Windows 10, [Firefox 129.0.1](https://download-installer.cdn.mozilla.net/pub/firefox/releases/129.0.1/win64/en-US/Firefox%20Setup%20129.0.1.exe), [Mailvelope 5.2.0](https://addons.mozilla.org/firefox/downloads/file/4310662/mailvelope-5.2.0.xpi), GnuPG 2.4.4.

By the way, my GnuPG is from [Gpg4win 4.3.0](https://files.gpg4win.org/gpg4win-4.3.0.exe) and the GnuPG is installed on my windows account `%LOCALAPPDATA%\gnupg\bin` 

My GnuPG isn't a global installation but a installation for standard local windows user. My Firefox is also installed to my local windows user.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/mailvelope/mailvelope/issues/814#issuecomment-2297430491

@rimmer:

1. ```sh
   sudo dnf5 install 'gnupg'
   sudo dnf5 install 'gpgme'
   ```
  
1. <blockQuote>

   ```log
   [sudo] password for RokeJulianLockhart: 
   Updating and loading repositories:
   Repositories loaded.
   Package "gnupg2-2.4.4-1.fc40.x86_64" is already installed.
  
   Nothing to do.
   Updating and loading repositories:
   Repositories loaded.
   Package "gpgme-1.23.2-3.fc40.x86_64" is already installed.
  
   Nothing to do.
   ```

   </blockQuote>

1. Irrespective, I continue to see:

   <blockQuote>

   ```HTML
   <div><div class="alert alert-info" role="alert"><div><strong>GnuPG is not available</strong></div><div><span>Do you have GnuPG installed? If not <a href="https://www.gnupg.org/download/index.html" target="_blank" rel="noopener noreferrer" class="btn btn-secondary btn-sm my-1" role="button">Download here</a>. To check availability again <button type="button" class="btn btn-secondary btn-sm">Restart Mailvelope</button>. If you are sure it is installed, please follow <a href="https://github.com/mailvelope/mailvelope/wiki/Mailvelope-GnuPG-integration" target="_blank" rel="noopener noreferrer">this wiki</a> to make sure it has been set up properly.</span></div></div></div>
   ```

   </blockQuote>

   However, in retrospect, this was probably because I didn't adhere entirely to https://github.com/mailvelope/mailvelope/wiki/Mailvelope-GnuPG-integration/5721fe7f1924df7c7fd121cc807af4003862a493#linux, by not creating https://github.com/mailvelope/mailvelope/wiki/Creating-the-app-manifest-file-on-macOS-and-Linux/3c6718d95f757034e5cf44574bc339b948eca5f1#firefox.

**Comment by shamefulCake1** [comment]
@rimmer on my Chromium setup gnupg can now be detected successfully.

Still, if it is not too much of an issue, would it be possible to check if the discovered version matches Mailvelope's expectations?

**Comment by rimmer** [comment]
> @rimmer on my Chromium setup gnupg can now be detected successfully.
> 
> Still, if it is not too much of an issue, would it be possible to check if the discovered version matches Mailvelope's expectations?

I personally see it as unnecessary because earlier versions may actually work. Like in your case, I assume.
