### ISSUE TITLE
Unable to sign only in Gmail

### ISSUE THREAD

**Issue by suicide** [mailvelope/mailvelope#867]
Setup:
Brave: Version 1.73.104 Chromium: 131.0.6778.204 (Official Build) (64-bit)
Mailvelope: 6.0.1 using GnuPG
Without gmail API

When I try to sign-only an email and select a key (none was pre-selected) nothing happens. Mailvelope remains open, email text in gmail stays empty

On the other hand, when I write an encrypted email, the ciphertext is pasted into gmail

**Comment by rimmer** [comment]
@suicide Hi, thanks for reporting. 
I was able to reproduce this with GnuPG on Chrome (not on Firefox though). 
Do you see your GnuPG keyring in Mailvelope's Key management?

After the changes in 6.0 we are aware of issues with GnuPG and are working on fixing them so we are hoping to fix this one as well. Stay tuned for the new release!

**Comment by suicide** [comment]
Yes, GnuPG
Weird, I just tried multiple keys (rsa and ed25519) all not working

**Comment by toberndo** [comment]
I fixed this now with: https://github.com/mailvelope/gpgmejs/commit/663e750b9e6ee487863d0028fbcf891cd12d3f58
Will be part of the next Mailvelope release.

**Comment by suicide** [comment]
@toberndo It is still not working.

weirdly enough, I now get a null pointer:
```
Error in event handler: ReferenceError: window is not defined
    at atobArray (chrome-extension://kajibbejlbohfaggdiogboambcijhkke/background.bundle.js:35338:17)
    at Answer.getMessage (chrome-extension://kajibbejlbohfaggdiogboambcijhkke/background.bundle.js:35736:33)
    at listener (chrome-extension://kajibbejlbohfaggdiogboambcijhkke/background.bundle.js:35572:52)
```

I always thought of `window` to be global?

**Comment by rimmer** [comment]
@suicide that's because we haven't released it yet https://github.com/mailvelope/mailvelope/commit/5ad6a025af0b53b611c5cfcf9a0da3b7890fe626.
